# Generated by Django 4.1.7 on 2023-10-28 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art_app', '0003_artist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artist',
            new_name='artists',
        ),
        migrations.CreateModel(
            name='arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(max_length=50, null=True)),
                ('arti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art_app.artists')),
            ],
        ),
    ]
