# Generated by Django 4.1.7 on 2023-10-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0004_rename_artist_artists_arts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arts',
            old_name='arti',
            new_name='artist',
        ),
    ]
