# Generated by Django 4.1.7 on 2023-10-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0005_rename_arti_arts_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arts',
            name='quantity',
        ),
    ]
