# Generated by Django 4.1.7 on 2023-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0006_remove_arts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
