# Generated by Django 4.1.7 on 2023-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0007_arts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
