# Generated by Django 4.1.7 on 2023-10-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0009_art_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_cart',
            name='profit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
