# Generated by Django 4.1.7 on 2023-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0010_art_cart_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_cart',
            name='profit',
        ),
        migrations.AddField(
            model_name='art_cart',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='art_cart',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
