# Generated by Django 4.1.7 on 2023-11-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0011_remove_art_cart_profit_art_cart_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_cart',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='art_cart',
            name='to_date',
        ),
        migrations.AddField(
            model_name='art_cart',
            name='profit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art_app.arts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art_app.users')),
            ],
        ),
    ]
