# Generated by Django 4.1.7 on 2023-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0012_remove_art_cart_from_date_remove_art_cart_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
