# Generated by Django 4.1.7 on 2023-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0013_rental_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
