# Generated by Django 4.1.7 on 2023-11-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0014_rental_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
