# Generated by Django 4.1.7 on 2023-11-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0015_rental_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='payment',
        ),
    ]
