# Generated by Django 4.1.7 on 2023-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0016_remove_rental_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_cart',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
